/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  poweredByHeader: false,
  typescript: { ignoreBuildErrors: false },
  eslint: { ignoreDuringBuilds: false },
  serverExternalPackages: ['@prisma/client', 'prisma', 'bcryptjs', 'nodemailer', 'ioredis'],
  transpilePackages: [
    '@cveriskpilot/domain',
    '@cveriskpilot/shared',
    '@cveriskpilot/auth',
    '@cveriskpilot/ai',
    '@cveriskpilot/billing',
    '@cveriskpilot/enrichment',
    '@cveriskpilot/parsers',
    '@cveriskpilot/storage',
    '@cveriskpilot/integrations',
    '@cveriskpilot/notifications',
    '@cveriskpilot/compliance',
    '@cveriskpilot/connectors',
    '@cveriskpilot/scan',
    '@cveriskpilot/stamps',
    '@cveriskpilot/streaming',
    '@cveriskpilot/db-scale',
    '@cveriskpilot/rollout',
    '@cveriskpilot/residency',
    '@cveriskpilot/backup',
    '@cveriskpilot/abac',
    '@cveriskpilot/observability',
    '@cveriskpilot/whitelabel',
    '@cveriskpilot/api-docs',
  ],
};

export default nextConfig;
