import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { scanDependencies } from '@cveriskpilot/scan';

// ---------------------------------------------------------------------------
// Fixtures — realistic Python dependency files
// ---------------------------------------------------------------------------

const POETRY_LOCK = `
# This file is automatically @generated by Poetry and should not be changed by hand.

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"
files = []

[package.dependencies]
certifi = ">=2017.4.17"
charset-normalizer = ">=2,<4"
idna = ">=2.5,<4"
urllib3 = ">=1.21.1,<3"

[[package]]
name = "certifi"
version = "2024.2.2"
description = "Python package for providing Mozilla's CA Bundle."
optional = false
python-versions = ">=3.6"
files = []

[[package]]
name = "flask"
version = "3.0.2"
description = "A simple framework for building complex web applications."
optional = false
python-versions = ">=3.8"
files = []

[[package]]
name = "click"
version = "8.1.7"
description = "Composable command line interface toolkit"
optional = false
python-versions = ">=3.7"
files = []

[metadata]
lock-version = "2.0"
python-versions = "^3.11"
content-hash = "abc123"
`;

const PYPROJECT_TOML_POETRY = `
[tool.poetry]
name = "my-python-app"
version = "1.0.0"
description = "A test Python project"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
flask = "^3.0.0"
pydantic = {version = "^2.5.0", extras = ["email"]}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^24.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
`;

const PYPROJECT_TOML_PEP621 = `
[project]
name = "my-pep621-app"
version = "1.0.0"
description = "A PEP 621 project"
dependencies = ["requests>=2.28", "click~=8.0", "pydantic>=2.0,<3.0"]

[project.optional-dependencies]
dev = ["pytest>=7.0"]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"
`;

const REQUIREMENTS_TXT = `
# Python dependencies
requests==2.31.0
flask==3.0.2
pydantic==2.5.3
click==8.1.7
# dev deps
pytest==7.4.4
`;

const PIPFILE_LOCK = JSON.stringify({
  _meta: { hash: { sha256: 'abc123' } },
  default: {
    requests: { version: '==2.31.0' },
    flask: { version: '==3.0.2' },
    pydantic: { version: '==2.5.3' },
  },
  develop: {
    pytest: { version: '==7.4.4' },
  },
});

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

let tmpDir: string;

function createFixtureDir(name: string, files: Record<string, string>): string {
  const dir = path.join(tmpDir, name);
  fs.mkdirSync(dir, { recursive: true });
  for (const [filename, content] of Object.entries(files)) {
    fs.writeFileSync(path.join(dir, filename), content, 'utf-8');
  }
  return dir;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Python dependency parsers', () => {
  beforeAll(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'crp-python-test-'));
  });

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('parses poetry.lock and extracts all packages', async () => {
    const dir = createFixtureDir('poetry-lock', {
      'poetry.lock': POETRY_LOCK,
      'pyproject.toml': PYPROJECT_TOML_POETRY,
    });

    const result = await scanDependencies(dir);

    expect(result.ecosystems).toContain('pip');
    expect(result.dependencies.length).toBeGreaterThanOrEqual(4);

    const requests = result.dependencies.find(d => d.name === 'requests');
    expect(requests).toBeDefined();
    expect(requests!.version).toBe('2.31.0');
    expect(requests!.ecosystem).toBe('pip');

    const certifi = result.dependencies.find(d => d.name === 'certifi');
    expect(certifi).toBeDefined();
    expect(certifi!.version).toBe('2024.2.2');

    const flask = result.dependencies.find(d => d.name === 'flask');
    expect(flask).toBeDefined();
    expect(flask!.version).toBe('3.0.2');

    const click = result.dependencies.find(d => d.name === 'click');
    expect(click).toBeDefined();
    expect(click!.version).toBe('8.1.7');
  });

  it('parses pyproject.toml with Poetry dependencies', async () => {
    const dir = createFixtureDir('pyproject-poetry', {
      'pyproject.toml': PYPROJECT_TOML_POETRY,
    });

    const result = await scanDependencies(dir);

    expect(result.ecosystems).toContain('pip');

    const requests = result.dependencies.find(d => d.name === 'requests');
    expect(requests).toBeDefined();
    expect(requests!.version).toBe('2.31.0');
    expect(requests!.direct).toBe(true);

    const flask = result.dependencies.find(d => d.name === 'flask');
    expect(flask).toBeDefined();
    expect(flask!.version).toBe('3.0.0');
    expect(flask!.direct).toBe(true);

    const pydantic = result.dependencies.find(d => d.name === 'pydantic');
    expect(pydantic).toBeDefined();
    expect(pydantic!.version).toBe('2.5.0');

    // python itself should NOT be included
    const python = result.dependencies.find(d => d.name === 'python');
    expect(python).toBeUndefined();
  });

  it('parses pyproject.toml with PEP 621 dependencies', async () => {
    const dir = createFixtureDir('pyproject-pep621', {
      'pyproject.toml': PYPROJECT_TOML_PEP621,
    });

    const result = await scanDependencies(dir);

    expect(result.ecosystems).toContain('pip');

    const requests = result.dependencies.find(d => d.name === 'requests');
    expect(requests).toBeDefined();
    expect(requests!.version).toBe('2.28');
    expect(requests!.direct).toBe(true);

    const click = result.dependencies.find(d => d.name === 'click');
    expect(click).toBeDefined();

    const pydantic = result.dependencies.find(d => d.name === 'pydantic');
    expect(pydantic).toBeDefined();
  });

  it('parses requirements.txt (existing parser still works)', async () => {
    const dir = createFixtureDir('requirements', {
      'requirements.txt': REQUIREMENTS_TXT,
    });

    const result = await scanDependencies(dir);

    expect(result.ecosystems).toContain('pip');
    expect(result.dependencies.length).toBe(5);

    const requests = result.dependencies.find(d => d.name === 'requests');
    expect(requests).toBeDefined();
    expect(requests!.version).toBe('2.31.0');
    expect(requests!.direct).toBe(true);
  });

  it('parses Pipfile.lock (existing parser still works)', async () => {
    const dir = createFixtureDir('pipfile', {
      'Pipfile.lock': PIPFILE_LOCK,
      'Pipfile': '[packages]\nrequests = "*"\n',
    });

    const result = await scanDependencies(dir);

    expect(result.ecosystems).toContain('pip');

    const requests = result.dependencies.find(d => d.name === 'requests');
    expect(requests).toBeDefined();
    expect(requests!.version).toBe('2.31.0');

    const pytest = result.dependencies.find(d => d.name === 'pytest');
    expect(pytest).toBeDefined();
    expect(pytest!.direct).toBe(false); // develop section
  });

  it('deduplicates when poetry.lock + pyproject.toml both present', async () => {
    const dir = createFixtureDir('poetry-both', {
      'poetry.lock': POETRY_LOCK,
      'pyproject.toml': PYPROJECT_TOML_POETRY,
    });

    const result = await scanDependencies(dir);

    // requests appears in both poetry.lock and pyproject.toml — should be deduped
    const requestsEntries = result.dependencies.filter(d => d.name === 'requests' && d.version === '2.31.0');
    expect(requestsEntries.length).toBe(1);
  });

  it('generates valid CycloneDX SBOM for Python projects', async () => {
    const dir = createFixtureDir('sbom-check', {
      'pyproject.toml': PYPROJECT_TOML_POETRY,
    });

    const result = await scanDependencies(dir);

    expect(result.sbom.bomFormat).toBe('CycloneDX');
    expect(result.sbom.specVersion).toBe('1.5');
    expect(result.sbom.components.length).toBeGreaterThan(0);

    // Check PURL format for PyPI packages
    const reqComponent = result.sbom.components.find(c => c.name === 'requests');
    expect(reqComponent).toBeDefined();
    expect(reqComponent!.purl).toMatch(/^pkg:pypi\/requests@/);
  });

  it('handles empty pyproject.toml with no dependencies', async () => {
    const dir = createFixtureDir('empty-pyproject', {
      'pyproject.toml': `
[project]
name = "empty-project"
version = "0.1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
`,
    });

    const result = await scanDependencies(dir);

    // Should not crash — may find 0 pip deps
    const pipDeps = result.dependencies.filter(d => d.ecosystem === 'pip');
    expect(pipDeps.length).toBe(0);
  });
});
