import { test, expect } from '@playwright/test';
import { loginAsUser } from './helpers/auth';
import { goToCases, waitForPageLoad } from './helpers/navigation';

const LOGIN_EMAIL = process.env.SMOKE_TEST_EMAIL || 'test@cveriskpilot.dev';
const LOGIN_PASSWORD = process.env.SMOKE_TEST_PASSWORD || 'TestPass123!';

/**
 * Navigate to the first available case detail page.
 * Reused across tests in this suite.
 */
async function navigateToFirstCase(page: import('@playwright/test').Page): Promise<void> {
  await loginAsUser(page, LOGIN_EMAIL, LOGIN_PASSWORD);
  await goToCases(page);

  const firstCase = page.locator('table tbody tr, [data-testid="case-row"]').first();
  await expect(firstCase).toBeVisible({ timeout: 15000 });
  await firstCase.click();

  await expect(page).toHaveURL(/\/cases\/[a-zA-Z0-9-]+/);
  await waitForPageLoad(page);
}

test.describe('AI Remediation', () => {
  // -----------------------------------------------------------------------
  // Button visibility
  // -----------------------------------------------------------------------

  test('get remediation button visible on case detail', async ({ page }) => {
    await navigateToFirstCase(page);

    const remediationButton = page
      .getByRole('button', { name: /get.*ai.*remediation|ai.*remediation|get.*remediation/i })
      .or(page.locator('[data-testid="ai-remediation-button"]'));
    await expect(remediationButton).toBeVisible({ timeout: 10000 });
  });

  // -----------------------------------------------------------------------
  // Loading state
  // -----------------------------------------------------------------------

  test('clicking get remediation shows loading state', async ({ page }) => {
    await navigateToFirstCase(page);

    const remediationButton = page
      .getByRole('button', { name: /get.*ai.*remediation|ai.*remediation|get.*remediation/i })
      .or(page.locator('[data-testid="ai-remediation-button"]'));
    await expect(remediationButton).toBeVisible({ timeout: 10000 });
    await remediationButton.click();

    // Expect loading spinner or loading text
    const loadingIndicator = page
      .getByText(/analyzing|generating|loading|processing/i)
      .or(page.locator('[data-testid="remediation-loading"]'))
      .or(page.locator('.animate-spin, .animate-pulse'));
    await expect(loadingIndicator).toBeVisible({ timeout: 5000 });
  });

  // -----------------------------------------------------------------------
  // Result display
  // -----------------------------------------------------------------------

  test('remediation result displays correctly', async ({ page }) => {
    await navigateToFirstCase(page);

    const remediationButton = page
      .getByRole('button', { name: /get.*ai.*remediation|ai.*remediation|get.*remediation/i })
      .or(page.locator('[data-testid="ai-remediation-button"]'));
    await expect(remediationButton).toBeVisible({ timeout: 10000 });
    await remediationButton.click();

    // Wait for loading to complete (may take a while with real AI)
    await waitForPageLoad(page);

    // Expect risk assessment section
    const riskSection = page
      .getByText(/risk assessment|risk analysis|severity/i)
      .or(page.locator('[data-testid="risk-assessment"]'));
    await expect(riskSection).toBeVisible({ timeout: 30000 });

    // Expect immediate actions / short-term fixes
    const immediateActions = page
      .getByText(/immediate action|quick fix|short.term|mitigation/i)
      .or(page.locator('[data-testid="immediate-actions"]'));
    await expect(immediateActions).toBeVisible();

    // Expect permanent fix section
    const permanentFix = page
      .getByText(/permanent fix|long.term|root cause|remediation/i)
      .or(page.locator('[data-testid="permanent-fix"]'));
    await expect(permanentFix).toBeVisible();

    // Expect verification steps
    const verification = page
      .getByText(/verification|verify|validation|testing/i)
      .or(page.locator('[data-testid="verification-steps"]'));
    await expect(verification).toBeVisible();

    // Expect "Generated by Claude" attribution badge
    const claudeBadge = page
      .getByText(/generated by claude|powered by claude|claude/i)
      .or(page.locator('[data-testid="claude-badge"]'));
    await expect(claudeBadge).toBeVisible();
  });

  // -----------------------------------------------------------------------
  // Copy to clipboard
  // -----------------------------------------------------------------------

  test('user can copy remediation to clipboard', async ({ page }) => {
    await navigateToFirstCase(page);

    // Trigger remediation
    const remediationButton = page
      .getByRole('button', { name: /get.*ai.*remediation|ai.*remediation|get.*remediation/i })
      .or(page.locator('[data-testid="ai-remediation-button"]'));
    await expect(remediationButton).toBeVisible({ timeout: 10000 });
    await remediationButton.click();

    // Wait for result to appear
    const riskSection = page
      .getByText(/risk assessment|risk analysis|severity/i)
      .or(page.locator('[data-testid="risk-assessment"]'));
    await expect(riskSection).toBeVisible({ timeout: 30000 });

    // Grant clipboard permissions in the browser context
    await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);

    // Click copy button
    const copyButton = page
      .getByRole('button', { name: /copy|clipboard/i })
      .or(page.locator('[data-testid="copy-remediation"]'));
    await expect(copyButton).toBeVisible({ timeout: 5000 });
    await copyButton.click();

    // Expect success toast / confirmation
    const successToast = page
      .getByText(/copied|clipboard/i)
      .or(page.locator('[data-testid="toast-success"]'));
    await expect(successToast).toBeVisible({ timeout: 5000 });
  });

  // -----------------------------------------------------------------------
  // Regenerate
  // -----------------------------------------------------------------------

  test('user can regenerate remediation', async ({ page }) => {
    await navigateToFirstCase(page);

    // Trigger initial remediation
    const remediationButton = page
      .getByRole('button', { name: /get.*ai.*remediation|ai.*remediation|get.*remediation/i })
      .or(page.locator('[data-testid="ai-remediation-button"]'));
    await expect(remediationButton).toBeVisible({ timeout: 10000 });
    await remediationButton.click();

    // Wait for result
    const riskSection = page
      .getByText(/risk assessment|risk analysis|severity/i)
      .or(page.locator('[data-testid="risk-assessment"]'));
    await expect(riskSection).toBeVisible({ timeout: 30000 });

    // Click regenerate
    const regenerateButton = page
      .getByRole('button', { name: /regenerate|retry|refresh/i })
      .or(page.locator('[data-testid="regenerate-remediation"]'));
    await expect(regenerateButton).toBeVisible({ timeout: 5000 });
    await regenerateButton.click();

    // Expect loading state again
    const loadingIndicator = page
      .getByText(/analyzing|generating|loading|processing/i)
      .or(page.locator('[data-testid="remediation-loading"]'))
      .or(page.locator('.animate-spin, .animate-pulse'));
    await expect(loadingIndicator).toBeVisible({ timeout: 5000 });

    // Expect new result to appear
    await expect(riskSection).toBeVisible({ timeout: 30000 });
  });

  // -----------------------------------------------------------------------
  // Rate limiting
  // -----------------------------------------------------------------------

  test('rate limit message shown when limit reached', async ({ page }) => {
    await navigateToFirstCase(page);

    // Mock the API to return a 429 rate-limit response
    await page.route('**/api/**/remediation**', (route) => {
      route.fulfill({
        status: 429,
        contentType: 'application/json',
        body: JSON.stringify({
          error: 'Rate limit exceeded',
          message: 'You have reached the maximum number of AI remediation requests.',
        }),
      });
    });

    // Click get remediation
    const remediationButton = page
      .getByRole('button', { name: /get.*ai.*remediation|ai.*remediation|get.*remediation/i })
      .or(page.locator('[data-testid="ai-remediation-button"]'));
    await expect(remediationButton).toBeVisible({ timeout: 10000 });
    await remediationButton.click();

    // Expect rate limit message
    const rateLimitMessage = page
      .getByText(/rate limit|too many requests|limit reached|maximum.*requests/i)
      .or(page.locator('[data-testid="rate-limit-message"]'));
    await expect(rateLimitMessage).toBeVisible({ timeout: 10000 });

    // Free users should see an upgrade prompt
    const upgradePrompt = page
      .getByRole('button', { name: /upgrade/i })
      .or(page.getByRole('link', { name: /upgrade/i }))
      .or(page.locator('[data-testid="upgrade-cta"]'));
    // This may or may not be visible depending on user tier; check without hard failure
    const upgradeVisible = await upgradePrompt.isVisible({ timeout: 3000 }).catch(() => false);
    if (upgradeVisible) {
      await expect(upgradePrompt).toBeVisible();
    }
  });
});
